export const itemsMen = [
  {
    id: 1,
    name: "AirFlex Runner",
    material: "Mesh & Synthetic",
    price: 89.99,
    weight: "1.1kg",
    colors: ["black", "white", "red"],
    description: "Lightweight running sneakers designed for comfort and speed.",
    image: "images/shoe1.jpg",
  },
  {
    id: 2,
    name: "StreetFlow Classic",
    material: "Leather",
    price: 119.99,
    weight: "1.3kg",
    colors: ["white", "navy"],
    description:
      "Timeless leather sneakers with a clean silhouette for everyday wear.",
    image: "images/shoe5.jpg",
  },
  {
    id: 3,
    name: "Urban Strike",
    material: "Canvas",
    price: 74.99,
    weight: "1.0kg",
    colors: ["black", "grey", "khaki"],
    description:
      "Casual sneakers made with durable canvas for street-ready style.",
    image: "images/shoe6.jpg",
  },
  {
    id: 4,
    name: "Peak Performance",
    material: "Knit Fabric",
    price: 99.99,
    weight: "0.9kg",
    colors: ["grey", "blue"],
    description:
      "Breathable knit sneakers that adapt to your foot for maximum comfort.",
    image: "images/shoe7.jpg",
  },
  {
    id: 5,
    name: "Velocity Pro",
    material: "Synthetic & Rubber",
    price: 109.99,
    weight: "1.2kg",
    colors: ["black", "orange", "lime"],
    description:
      "Performance sneakers with shock-absorbing soles for athletes.",
    image: "images/shoe8.jpg",
  },
  {
    id: 6,
    name: "Retro Runner 90s",
    material: "Leather & Suede",
    price: 129.99,
    weight: "1.4kg",
    colors: ["white", "green", "purple"],
    description:
      "Retro-inspired sneakers combining modern comfort with 90s style.",
    image: "images/shoe9.jpg",
  },
  {
    id: 7,
    name: "Summit Trek",
    material: "Synthetic & Mesh",
    price: 139.99,
    weight: "1.5kg",
    colors: ["olive", "black", "beige"],
    description:
      "Rugged sneakers built for both city adventures and light hiking.",
    image: "images/shoe10.jpg",
  },
  {
    id: 8,
    name: "NightShift Low",
    material: "Canvas & Rubber",
    price: 69.99,
    weight: "1.0kg",
    colors: ["black", "white"],
    description:
      "Minimalist sneakers with a versatile low-top design for any outfit.",
    image: "images/shoe11.jpg",
  },
  {
    id: 9,
    name: "Pulse Ignite",
    material: "Knit & Foam",
    price: 94.99,
    weight: "1.0kg",
    colors: ["red", "grey", "black"],
    description:
      "Lightweight training sneakers with high-energy foam cushioning.",
    image: "images/shoe12.jpg",
  },
  {
    id: 10,
    name: "AeroDash",
    material: "Mesh & Rubber",
    price: 84.99,
    weight: "0.95kg",
    colors: ["blue", "white"],
    description:
      "Breathable mesh sneakers with flexible soles for dynamic movement.",
    image: "images/shoe13.jpg",
  },
  {
    id: 11,
    name: "Titan High",
    material: "Leather",
    price: 149.99,
    weight: "1.6kg",
    colors: ["black", "white", "burgundy"],
    description:
      "High-top sneakers with premium leather for durability and style.",
    image: "images/shoe14.jpg",
  },
  {
    id: 12,
    name: "Swift Motion",
    material: "Knit & Rubber",
    price: 89.99,
    weight: "1.1kg",
    colors: ["grey", "blue", "orange"],
    description: "Flexible sneakers designed for running and all-day comfort.",
    image: "images/shoe15.jpg",
  },
  {
    id: 13,
    name: "Core Essential",
    material: "Canvas",
    price: 59.99,
    weight: "0.9kg",
    colors: ["white", "black"],
    description:
      "Everyday sneakers with a classic canvas design at an affordable price.",
    image: "images/shoe16.jpg",
  },
  {
    id: 14,
    name: "Glide X",
    material: "Synthetic",
    price: 99.99,
    weight: "1.2kg",
    colors: ["navy", "grey", "white"],
    description:
      "Modern sneakers with slip-resistant soles for versatile wear.",
    image: "images/shoe17.jpg",
  },
  {
    id: 15,
    name: "Fusion Edge",
    material: "Leather & Mesh",
    price: 129.99,
    weight: "1.3kg",
    colors: ["black", "gold", "white"],
    description:
      "Bold sneakers that fuse streetwear style with athletic performance.",
    image: "images/shoe18.jpg",
  },
  {
    id: 16,
    name: "Urban Stride",
    material: "Synthetic Leather",
    price: 114.99,
    weight: "1.2kg",
    colors: ["navy", "white"],
    description:
      "A versatile high-top designed for comfort and everyday city wear.",
    image: "images/shoe19.jpg",
  },
];

export const itemsWomen = [
  {
    id: 17,
    name: "Luna Breeze",
    material: "Mesh & Synthetic",
    price: 89.99,
    weight: "0.9kg",
    colors: ["white", "pink", "grey"],
    description:
      "Lightweight running sneakers with a breathable design for all-day comfort.",
    image: "images/shoe20.jpg",
  },
  {
    id: 18,
    name: "Velvet Street",
    material: "Leather",
    price: 119.99,
    weight: "1.1kg",
    colors: ["white", "beige"],
    description:
      "Elegant leather sneakers that blend everyday comfort with chic style.",
    image: "images/shoe21.jpg",
  },
  {
    id: 19,
    name: "Bloom Classic",
    material: "Canvas",
    price: 69.99,
    weight: "0.85kg",
    colors: ["lavender", "white", "black"],
    description:
      "Classic canvas sneakers with soft pastel tones for casual wear.",
    image: "images/shoe22.jpg",
  },
  {
    id: 20,
    name: "Aero Grace",
    material: "Knit Fabric",
    price: 94.99,
    weight: "0.8kg",
    colors: ["mint", "white", "grey"],
    description:
      "Ultra-light knit sneakers that adapt to your step with style and comfort.",
    image: "images/shoe23.jpg",
  },
  {
    id: 21,
    name: "Nova Energy",
    material: "Synthetic & Rubber",
    price: 109.99,
    weight: "1.0kg",
    colors: ["black", "pink", "teal"],
    description:
      "High-performance sneakers with cushioned soles and a sleek design.",
    image: "images/shoe24.jpg",
  },
  {
    id: 22,
    name: "Retro Blossom",
    material: "Leather & Suede",
    price: 129.99,
    weight: "1.2kg",
    colors: ["white", "rose", "turquoise"],
    description:
      "Retro-inspired sneakers with soft suede details and vibrant colors.",
    image: "images/shoe25.jpg",
  },
  {
    id: 23,
    name: "Summit Trail",
    material: "Synthetic & Mesh",
    price: 139.99,
    weight: "1.3kg",
    colors: ["beige", "olive", "pink"],
    description:
      "Durable sneakers for light hikes and city walks with a feminine touch.",
    image: "images/shoe26.jpg",
  },
  {
    id: 24,
    name: "NightBloom Low",
    material: "Canvas & Rubber",
    price: 64.99,
    weight: "0.85kg",
    colors: ["black", "white", "rose"],
    description:
      "Low-top sneakers with minimal design and floral-inspired colorways.",
    image: "images/shoe27.jpg",
  },
  {
    id: 25,
    name: "Pulse Glow",
    material: "Knit & Foam",
    price: 92.99,
    weight: "0.9kg",
    colors: ["pink", "purple", "grey"],
    description:
      "Training sneakers with energizing foam cushioning and bright colors.",
    image: "images/shoe28.jpg",
  },
  {
    id: 26,
    name: "SkyDash",
    material: "Mesh & Rubber",
    price: 84.99,
    weight: "0.8kg",
    colors: ["blue", "white", "coral"],
    description:
      "Breathable sneakers with flexible soles for active lifestyles.",
    image: "images/shoe29.jpg",
  },
  {
    id: 27,
    name: "Titan Rose High",
    material: "Leather",
    price: 149.99,
    weight: "1.4kg",
    colors: ["white", "rose", "black"],
    description:
      "Premium leather high-top sneakers with bold, feminine detailing.",
    image: "images/shoe30.jpg",
  },
  {
    id: 28,
    name: "Swift Blossom",
    material: "Knit & Rubber",
    price: 89.99,
    weight: "0.9kg",
    colors: ["lavender", "grey", "white"],
    description:
      "Flexible knit sneakers designed for speed and comfort on the move.",
    image: "images/shoe31.jpg",
  },
];

export const popularProducts = [
  {
    id: 1,
    name: "AirFlex Runner",
    material: "Mesh & Synthetic",
    price: 89.99,
    weight: "1.1kg",
    colors: ["black", "white", "red"],
    description: "Lightweight running sneakers designed for comfort and speed.",
    image: "images/shoe1.jpg",
  },
  {
    id: 4,
    name: "Peak Performance",
    material: "Knit Fabric",
    price: 99.99,
    weight: "0.9kg",
    colors: ["grey", "blue"],
    description:
      "Breathable knit sneakers that adapt to your foot for maximum comfort.",
    image: "images/shoe7.jpg",
  },
  {
    id: 7,
    name: "Summit Trek",
    material: "Synthetic & Mesh",
    price: 139.99,
    weight: "1.5kg",
    colors: ["olive", "black", "beige"],
    description:
      "Rugged sneakers built for both city adventures and light hiking.",
    image: "images/shoe10.jpg",
  },
  {
    id: 11,
    name: "Titan High",
    material: "Leather",
    price: 149.99,
    weight: "1.6kg",
    colors: ["black", "white", "burgundy"],
    description:
      "High-top sneakers with premium leather for durability and style.",
    image: "images/shoe14.jpg",
  },
  {
    id: 17,
    name: "Luna Breeze",
    material: "Mesh & Synthetic",
    price: 89.99,
    weight: "0.9kg",
    colors: ["white", "pink", "grey"],
    description:
      "Lightweight running sneakers with a breathable design for all-day comfort.",
    image: "images/shoe20.jpg",
  },
  {
    id: 20,
    name: "Aero Grace",
    material: "Knit Fabric",
    price: 94.99,
    weight: "0.8kg",
    colors: ["mint", "white", "grey"],
    description:
      "Ultra-light knit sneakers that adapt to your step with style and comfort.",
    image: "images/shoe23.jpg",
  },
  {
    id: 22,
    name: "Retro Blossom",
    material: "Leather & Suede",
    price: 129.99,
    weight: "1.2kg",
    colors: ["white", "rose", "turquoise"],
    description:
      "Retro-inspired sneakers with soft suede details and vibrant colors.",
    image: "images/shoe25.jpg",
  },
  {
    id: 27,
    name: "Titan Rose High",
    material: "Leather",
    price: 149.99,
    weight: "1.4kg",
    colors: ["white", "rose", "black"],
    description:
      "Premium leather high-top sneakers with bold, feminine detailing.",
    image: "images/shoe30.jpg",
  },
];

export const newProducts = [
  {
    id: 1,
    name: "AirFlex Runner",
    material: "Mesh & Synthetic",
    price: 89.99,
    weight: "1.1kg",
    colors: ["black", "white", "red"],
    description: "Lightweight running sneakers designed for comfort and speed.",
    image: "images/shoe1.jpg",
  },
  {
    id: 6,
    name: "Retro Runner 90s",
    material: "Leather & Suede",
    price: 129.99,
    weight: "1.4kg",
    colors: ["white", "green", "purple"],
    description:
      "Retro-inspired sneakers combining modern comfort with 90s style.",
    image: "images/shoe9.jpg",
  },
  {
    id: 11,
    name: "Titan High",
    material: "Leather",
    price: 149.99,
    weight: "1.6kg",
    colors: ["black", "white", "burgundy"],
    description:
      "High-top sneakers with premium leather for durability and style.",
    image: "images/shoe14.jpg",
  },
  {
    id: 16,
    name: "Urban Stride",
    material: "Synthetic Leather",
    price: 114.99,
    weight: "1.2kg",
    colors: ["navy", "white"],
    description:
      "A versatile high-top designed for comfort and everyday city wear.",
    image: "images/shoe19.jpg",
  },
  {
    id: 17,
    name: "Luna Breeze",
    material: "Mesh & Synthetic",
    price: 89.99,
    weight: "0.9kg",
    colors: ["white", "pink", "grey"],
    description:
      "Lightweight running sneakers with a breathable design for all-day comfort.",
    image: "images/shoe20.jpg",
  },
  {
    id: 22,
    name: "Retro Blossom",
    material: "Leather & Suede",
    price: 129.99,
    weight: "1.2kg",
    colors: ["white", "rose", "turquoise"],
    description:
      "Retro-inspired sneakers with soft suede details and vibrant colors.",
    image: "images/shoe25.jpg",
  },
  {
    id: 25,
    name: "Pulse Glow",
    material: "Knit & Foam",
    price: 92.99,
    weight: "0.9kg",
    colors: ["pink", "purple", "grey"],
    description:
      "Training sneakers with energizing foam cushioning and bright colors.",
    image: "images/shoe28.jpg",
  },
  {
    id: 27,
    name: "Titan Rose High",
    material: "Leather",
    price: 149.99,
    weight: "1.4kg",
    colors: ["white", "rose", "black"],
    description:
      "Premium leather high-top sneakers with bold, feminine detailing.",
    image: "images/shoe30.jpg",
  },
];
